[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
thiserror = "1.0"
ssh2 = "0.9.4"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1.8.4", features = ["full"] }
regex = "1"
slack-hook = "0.8.0"
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
